@startuml
AppUser -> Webserver: Get https://xxx/orders?uuid=123
Webserver --> OrderController: uuid
OrderController --> OrderService: uuid
OrderService --> OrderDao: uuid
OrderDao --> OrderService: List<OrderPO>
OrderService --> OrderController: List<OrderVO>
OrderController --> Webserver: List<OrderVO>
AppUser <-- Webserver
@enduml