@startuml
AppUser -> Webserver: Update https://xxx/orders/{OrderId}?uuid=123
Webserver --> OrderController: OrderId
OrderController --> OrderService: OrderId
OrderService --> OrderDao: OrderId
OrderDao --> OrderService: OrderPO
OrderService --> OrderController: OrderVO
OrderController --> Webserver: OrderVO
AppUser <-- Webserver
@enduml